export interface PageTemplate {
  id: string;
  name: string;
  category: 'SALES_PAGE' | 'OPTIN_PAGE' | 'THANK_YOU_PAGE' | 'CHECKOUT_PAGE' | 'CUSTOM_PAGE';
  description: string;
  badge: string;
  badgeColor: string;
  previewBg: string;
  themeColor: string;
  contentJson: any;
}

// 🟢 CLONE DU TEMPLATE VERT: DIGITAL PRODUCT PRO SALES PAGE
export const GREEN_DIGITAL_SALES_PAGE_JSON = {
  ROOT: {
    type: { resolvedName: 'Container' },
    isCanvas: true,
    props: {
      bgColor: '#022c22',
      padding: 0,
      width: 100,
      pageLayoutMode: 'full',
    },
    displayName: 'Page Racine (Template Vert)',
    custom: {},
    hidden: false,
    nodes: [
      'announcement-bar',
      'hero-grid',
      'skills-section',
      'cta-middle-banner',
      'story-grid',
      'curriculum-section',
      'before-after-section',
      'pricing-card-section',
      'faq-section',
      'final-cta-section',
    ],
    linkedNodes: {},
  },

  // 1. BANDEAU ROUGE SUPÉRIEUR
  'announcement-bar': {
    type: { resolvedName: 'Text' },
    isCanvas: false,
    props: {
      text: '🔥 OFFRE SPÉCIALE HORS-SÉRIE ! PLACES LIMITÉES — GARANTIE REMBOURSEMENT 30 JOURS',
      fontSize: 13,
      textAlign: 'center',
      textColor: '#ffffff',
      bgColor: '#dc2626',
      paddingTop: 10,
      paddingBottom: 10,
      paddingLeft: 16,
      paddingRight: 16,
      fontWeight: 'bold',
    },
    displayName: 'Bandeau Urgence Rouge',
    parent: 'ROOT',
  },

  // 2. HERO GRID SECTION
  'hero-grid': {
    type: { resolvedName: 'Grid' },
    isCanvas: false,
    props: {
      columns: 1,
      bgColor: '#022c22',
      paddingTop: 48,
      paddingBottom: 48,
      paddingLeft: 24,
      paddingRight: 24,
    },
    displayName: 'Section Hero Principale',
    parent: 'ROOT',
    nodes: ['hero-container'],
  },
  'hero-container': {
    type: { resolvedName: 'Container' },
    isCanvas: true,
    props: {
      bgColor: 'transparent',
      padding: 0,
      width: 100,
    },
    displayName: 'Hero Container',
    parent: 'hero-grid',
    nodes: ['hero-title', 'hero-subtitle', 'hero-video', 'hero-cta-button'],
  },
  'hero-title': {
    type: { resolvedName: 'Text' },
    isCanvas: false,
    props: {
      text: '🚀 Lancez Votre Produit Numérique Rentable — Même Si Vous Partez de Zéro',
      fontSize: 40,
      textAlign: 'center',
      textColor: '#ffffff',
      fontWeight: 'black',
      marginBottom: 16,
      highlightColor: '#15803d',
      highlightPadding: 8,
    },
    displayName: 'Titre Hero',
    parent: 'hero-container',
  },
  'hero-subtitle': {
    type: { resolvedName: 'Text' },
    isCanvas: false,
    props: {
      text: 'Découvrez la méthode exacte étape par étape pour concevoir, lancer et automatiser les ventes de vos produits digitaux avec notre framework clé en main.',
      fontSize: 18,
      textAlign: 'center',
      textColor: '#86efac',
      fontWeight: 'normal',
      marginBottom: 32,
    },
    displayName: 'Sous-titre Hero',
    parent: 'hero-container',
  },
  'hero-video': {
    type: { resolvedName: 'Video' },
    isCanvas: false,
    props: {
      videoUrl: 'https://www.youtube.com/embed/dQw4w9WgXcQ',
      caption: '🎙️ Regardez la présentation exclusive en direct (12 min)',
      width: 90,
      marginBottom: 32,
    },
    displayName: 'Vidéo Présentation',
    parent: 'hero-container',
  },
  'hero-cta-button': {
    type: { resolvedName: 'Button' },
    isCanvas: false,
    props: {
      text: '👉 Obtenir Mon Accès Immédiat Pour 19€ Seulement',
      bgColor: '#22c55e',
      textColor: '#022c22',
      fontSize: 18,
      fontWeight: 'black',
      borderRadius: 999,
      paddingY: 18,
      paddingX: 36,
      align: 'center',
      href: '#pricing',
    },
    displayName: 'Bouton CTA Hero',
    parent: 'hero-container',
  },

  // 3. SKILLS GRID SECTION (COMPÉTENCES)
  'skills-section': {
    type: { resolvedName: 'Grid' },
    isCanvas: false,
    props: {
      columns: 1,
      bgColor: '#064e3b',
      paddingTop: 56,
      paddingBottom: 56,
      paddingLeft: 24,
      paddingRight: 24,
    },
    displayName: 'Section Grille de Compétences',
    parent: 'ROOT',
    nodes: ['skills-container'],
  },
  'skills-container': {
    type: { resolvedName: 'Container' },
    isCanvas: true,
    props: {
      bgColor: 'transparent',
      padding: 0,
      width: 100,
    },
    displayName: 'Skills Container',
    parent: 'skills-section',
    nodes: ['skills-title', 'skills-feature-grid'],
  },
  'skills-title': {
    type: { resolvedName: 'Text' },
    isCanvas: false,
    props: {
      text: '🎯 Les Compétences Clés Pour Transformer Vos Idées En Revenus',
      fontSize: 32,
      textAlign: 'center',
      textColor: '#ffffff',
      fontWeight: 'black',
      marginBottom: 32,
    },
    displayName: 'Titre Compétences',
    parent: 'skills-container',
  },
  'skills-feature-grid': {
    type: { resolvedName: 'FeatureGrid' },
    isCanvas: false,
    props: {
      columns: 4,
      items: [
        {
          title: '🔍 Niche Rentable',
          desc: 'Identifiez précisément les sujets les plus recherchés et monétisables.',
          img: 'https://images.unsplash.com/photo-1545241047-6083a3684587?auto=format&fit=crop&w=400&q=80',
        },
        {
          title: '📦 Offre Irrésistible',
          desc: 'Structurez un produit numérique à forte valeur ajoutée en quelques jours.',
          img: 'https://images.unsplash.com/photo-1546069901-ba9599a7e63c?auto=format&fit=crop&w=400&q=80',
        },
        {
          title: '📈 Stratégie Prix',
          desc: 'Fixez les meilleurs tarifs pour maximiser vos conversions sans brader.',
          img: 'https://images.unsplash.com/photo-1585320806297-9794b3e4eeae?auto=format&fit=crop&w=400&q=80',
        },
        {
          title: '🚀 Ventes en Automatique',
          desc: 'Automatisez la livraison et le suivi client pour encaisser en continu.',
          img: 'https://images.unsplash.com/photo-1540420773420-3366772f4999?auto=format&fit=crop&w=400&q=80',
        },
      ],
      imgHeight: 180,
      borderRadius: 16,
    },
    displayName: 'Grille 4 Colonnes',
    parent: 'skills-container',
  },

  // 4. CTA BANNER MIDDLE
  'cta-middle-banner': {
    type: { resolvedName: 'Container' },
    isCanvas: false,
    props: {
      bgColor: '#047857',
      paddingTop: 36,
      paddingBottom: 36,
      paddingLeft: 24,
      paddingRight: 24,
      borderRadius: 24,
      marginTop: 32,
      marginBottom: 32,
      width: 95,
    },
    displayName: 'Bandeau CTA Intermédiaire',
    parent: 'ROOT',
    nodes: ['cta-banner-text', 'cta-banner-button'],
  },
  'cta-banner-text': {
    type: { resolvedName: 'Text' },
    isCanvas: false,
    props: {
      text: '⚡ Commencez à Créer Votre Produit Numérique Aujourd hui',
      fontSize: 26,
      textAlign: 'center',
      textColor: '#ffffff',
      fontWeight: 'black',
      marginBottom: 16,
    },
    displayName: 'Titre Bandeau CTA',
    parent: 'cta-middle-banner',
  },
  'cta-banner-button': {
    type: { resolvedName: 'Button' },
    isCanvas: false,
    props: {
      text: '👉 Débloquer l Accès Immédiat (19€)',
      bgColor: '#4ade80',
      textColor: '#052e16',
      fontSize: 16,
      fontWeight: 'black',
      borderRadius: 999,
      paddingY: 16,
      paddingX: 32,
      align: 'center',
      href: '#pricing',
    },
    displayName: 'Bouton Bandeau CTA',
    parent: 'cta-middle-banner',
  },

  // 5. STORY SECTION (FORMATEUR)
  'story-grid': {
    type: { resolvedName: 'Grid' },
    isCanvas: false,
    props: {
      columns: 2,
      columnWidths: [50, 50],
      bgColor: '#022c22',
      paddingTop: 48,
      paddingBottom: 48,
      paddingLeft: 24,
      paddingRight: 24,
    },
    displayName: 'Section Histoire / Formateur',
    parent: 'ROOT',
    nodes: ['story-col-1', 'story-col-2'],
  },
  'story-col-1': {
    type: { resolvedName: 'Container' },
    isCanvas: true,
    props: {
      bgColor: 'transparent',
      padding: 0,
      width: 100,
    },
    displayName: 'Story Col 1',
    parent: 'story-grid',
    nodes: ['story-image'],
  },
  'story-image': {
    type: { resolvedName: 'Image' },
    isCanvas: false,
    props: {
      src: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?auto=format&fit=crop&w=600&q=80',
      alt: 'Sophie - Formatrice',
      height: 380,
      borderRadius: 24,
      align: 'center',
    },
    displayName: 'Photo Formateur',
    parent: 'story-col-1',
  },
  'story-col-2': {
    type: { resolvedName: 'Container' },
    isCanvas: true,
    props: {
      bgColor: 'transparent',
      padding: 0,
      width: 100,
    },
    displayName: 'Story Col 2',
    parent: 'story-grid',
    nodes: ['story-title', 'story-text'],
  },
  'story-title': {
    type: { resolvedName: 'Text' },
    isCanvas: false,
    props: {
      text: '👋 Des Idées Simples Vers Des Produits Qui Se Vendent Seuls',
      fontSize: 28,
      textAlign: 'left',
      textColor: '#ffffff',
      fontWeight: 'black',
      marginBottom: 16,
    },
    displayName: 'Titre Histoire',
    parent: 'story-col-2',
  },
  'story-text': {
    type: { resolvedName: 'Text' },
    isCanvas: false,
    props: {
      text: 'Bonjour, je suis Sophie. Après avoir aidé plus de 1500 créateurs à lancer leurs offres digitales, j ai condensé tout notre système dans ce guide pratique et directement applicable.<br/><br/>✔ <b>100% Pratique</b> : Pas de théorie inutile.<br/>✔ <b>Templates inclus</b> : Copiez-collez nos structures de vente.<br/>✔ <b>Gain de temps massif</b> : Gagnez des mois de travail.',
      fontSize: 15,
      textAlign: 'left',
      textColor: '#cbd5e1',
      fontWeight: 'normal',
    },
    displayName: 'Texte Histoire',
    parent: 'story-col-2',
  },

  // 6. PROGRAMME DÉTAILLÉ (CURRICULUM)
  'curriculum-section': {
    type: { resolvedName: 'Grid' },
    isCanvas: false,
    props: {
      columns: 1,
      bgColor: '#064e3b',
      paddingTop: 56,
      paddingBottom: 56,
      paddingLeft: 24,
      paddingRight: 24,
    },
    displayName: 'Section Programme / Modules',
    parent: 'ROOT',
    nodes: ['curriculum-container'],
  },
  'curriculum-container': {
    type: { resolvedName: 'Container' },
    isCanvas: true,
    props: {
      bgColor: 'transparent',
      padding: 0,
      width: 100,
    },
    displayName: 'Curriculum Container',
    parent: 'curriculum-section',
    nodes: ['curriculum-title', 'curriculum-card-1', 'curriculum-card-2', 'curriculum-card-3'],
  },
  'curriculum-title': {
    type: { resolvedName: 'Text' },
    isCanvas: false,
    props: {
      text: '📚 Explorez Le Contenu Détaillé Des Modules',
      fontSize: 32,
      textAlign: 'center',
      textColor: '#ffffff',
      fontWeight: 'black',
      marginBottom: 32,
    },
    displayName: 'Titre Curriculum',
    parent: 'curriculum-container',
  },
  'curriculum-card-1': {
    type: { resolvedName: 'Card' },
    isCanvas: false,
    props: {
      title: '📦 Module 1 & 2 : Validation de Niche & Création de l Offre',
      content: 'Apprenez à identifier les besoins urgents de votre audience et créez un produit au format parfait (Ebook, Template Notion, Masterclass).',
      bgColor: '#022c22',
      padding: 24,
      borderRadius: 16,
      marginBottom: 16,
    },
    displayName: 'Carte Module 1',
    parent: 'curriculum-container',
  },
  'curriculum-card-2': {
    type: { resolvedName: 'Card' },
    isCanvas: false,
    props: {
      title: '📈 Module 3 & 4 : Tarification & Systemes de Vente Automatisés',
      content: 'Configurez vos pages de vente sans aucune compétence technique et automatisez la réception des paiements 24/7.',
      bgColor: '#022c22',
      padding: 24,
      borderRadius: 16,
      marginBottom: 16,
    },
    displayName: 'Carte Module 2',
    parent: 'curriculum-container',
  },
  'curriculum-card-3': {
    type: { resolvedName: 'Card' },
    isCanvas: false,
    props: {
      title: '🚀 Module 5 & 6 : Trafic Qualifié & Automatisation des Résultats',
      content: 'Découvrez comment attirer des acheteurs qualifiés quotidiennement sans dépenser une fortune en publicité.',
      bgColor: '#022c22',
      padding: 24,
      borderRadius: 16,
      marginBottom: 24,
    },
    displayName: 'Carte Module 3',
    parent: 'curriculum-container',
  },

  // 7. AVANT / APRÈS (BEFORE & AFTER)
  'before-after-section': {
    type: { resolvedName: 'Grid' },
    isCanvas: false,
    props: {
      columns: 2,
      columnWidths: [50, 50],
      bgColor: '#022c22',
      paddingTop: 56,
      paddingBottom: 56,
      paddingLeft: 24,
      paddingRight: 24,
    },
    displayName: 'Section Avant / Après',
    parent: 'ROOT',
    nodes: ['before-col', 'after-col'],
  },
  'before-col': {
    type: { resolvedName: 'Card' },
    isCanvas: false,
    props: {
      title: '🔴 Avant Cette Formation :',
      content: '• Idées floues et hésitations permanentes<br/>• Des semaines perdues sans aucun résultat<br/>• Blocages techniques sur les outils<br/>• Frustration et doutes réguliers',
      bgColor: '#450a0a',
      padding: 28,
      borderRadius: 20,
    },
    displayName: 'Carte Avant',
    parent: 'before-after-section',
  },
  'after-col': {
    type: { resolvedName: 'Card' },
    isCanvas: false,
    props: {
      title: '🟢 Après Cette Formation :',
      content: '✔ Un produit numérique clair et prêt à vendre<br/>✔ Une page de vente professionnelle active 24/7<br/>✔ Encaissements automatisés directement sur votre compte<br/>✔ Clarté et confiance totale dans votre business',
      bgColor: '#064e3b',
      padding: 28,
      borderRadius: 20,
    },
    displayName: 'Carte Après',
    parent: 'before-after-section',
  },

  // 8. PRICING OFFER SECTION (OFFRE SPÉCIALE)
  'pricing-card-section': {
    type: { resolvedName: 'Container' },
    isCanvas: false,
    props: {
      bgColor: '#064e3b',
      paddingTop: 48,
      paddingBottom: 48,
      paddingLeft: 32,
      paddingRight: 32,
      borderRadius: 32,
      marginTop: 40,
      marginBottom: 40,
      width: 90,
      shadowPreset: 'xl',
    },
    displayName: 'Section Tarif & Offre Spéciale',
    parent: 'ROOT',
    nodes: ['pricing-badge', 'pricing-title', 'pricing-price', 'pricing-features', 'pricing-button'],
  },
  'pricing-badge': {
    type: { resolvedName: 'Text' },
    isCanvas: false,
    props: {
      text: '🎁 OFFRE D ACCÈS IMMÉDIAT 100% GARANTIE',
      fontSize: 12,
      textAlign: 'center',
      textColor: '#22c55e',
      fontWeight: 'black',
      marginBottom: 12,
    },
    displayName: 'Badge Offre',
    parent: 'pricing-card-section',
  },
  'pricing-title': {
    type: { resolvedName: 'Text' },
    isCanvas: false,
    props: {
      text: 'Seulement 19€ En Paiement Unique',
      fontSize: 34,
      textAlign: 'center',
      textColor: '#ffffff',
      fontWeight: 'black',
      marginBottom: 8,
    },
    displayName: 'Titre Prix',
    parent: 'pricing-card-section',
  },
  'pricing-price': {
    type: { resolvedName: 'Text' },
    isCanvas: false,
    props: {
      text: '(Valeur habituelle : <s style="opacity:0.6">197€</s> — Réduction exceptionnelle de -90%)',
      fontSize: 14,
      textAlign: 'center',
      textColor: '#a7f3d0',
      marginBottom: 24,
    },
    displayName: 'Sous-titre Prix',
    parent: 'pricing-card-section',
  },
  'pricing-features': {
    type: { resolvedName: 'Text' },
    isCanvas: false,
    props: {
      text: '✔ Accès complet et illimité à la méthode<br/>✔ Pack complet de templates de vente prêts à l emploi<br/>✔ Mises à jour gratuites à vie<br/>✔ Garantie Satisfait ou Remboursé 30 Jours sans condition',
      fontSize: 15,
      textAlign: 'center',
      textColor: '#ffffff',
      fontWeight: 'bold',
      marginBottom: 32,
    },
    displayName: 'Liste des Avantages',
    parent: 'pricing-card-section',
  },
  'pricing-button': {
    type: { resolvedName: 'Button' },
    isCanvas: false,
    props: {
      text: '🛒 Valider Mon Accès Pour 19€ (Accès Immédiat)',
      bgColor: '#22c55e',
      textColor: '#022c22',
      fontSize: 18,
      fontWeight: 'black',
      borderRadius: 999,
      paddingY: 18,
      paddingX: 36,
      align: 'center',
      href: '#checkout',
    },
    displayName: 'Bouton Commander',
    parent: 'pricing-card-section',
  },

  // 9. FAQ SECTION
  'faq-section': {
    type: { resolvedName: 'Grid' },
    isCanvas: false,
    props: {
      columns: 1,
      bgColor: '#022c22',
      paddingTop: 48,
      paddingBottom: 48,
      paddingLeft: 24,
      paddingRight: 24,
    },
    displayName: 'Section Questions Fréquentes',
    parent: 'ROOT',
    nodes: ['faq-container'],
  },
  'faq-container': {
    type: { resolvedName: 'Container' },
    isCanvas: true,
    props: {
      bgColor: 'transparent',
      padding: 0,
      width: 100,
    },
    displayName: 'FAQ Container',
    parent: 'faq-section',
    nodes: ['faq-title', 'faq-card-1', 'faq-card-2'],
  },
  'faq-title': {
    type: { resolvedName: 'Text' },
    isCanvas: false,
    props: {
      text: '❓ Questions Fréquemment Posées',
      fontSize: 28,
      textAlign: 'center',
      textColor: '#ffffff',
      fontWeight: 'black',
      marginBottom: 24,
    },
    displayName: 'Titre FAQ',
    parent: 'faq-container',
  },
  'faq-card-1': {
    type: { resolvedName: 'Card' },
    isCanvas: false,
    props: {
      title: 'Est-ce adapté aux débutants sans expérience ?',
      content: 'Oui, absolument ! La méthode est conçue pas à pas, sans jargon technique incompréhensible.',
      bgColor: '#064e3b',
      padding: 20,
      borderRadius: 16,
      marginBottom: 12,
    },
    displayName: 'FAQ Item 1',
    parent: 'faq-container',
  },
  'faq-card-2': {
    type: { resolvedName: 'Card' },
    isCanvas: false,
    props: {
      title: 'Combien de temps ai-je accès à la formation ?',
      content: 'Vous bénéficiez d un accès illimité à vie, incluant toutes les futures mises à jour gratuites.',
      bgColor: '#064e3b',
      padding: 20,
      borderRadius: 16,
      marginBottom: 24,
    },
    displayName: 'FAQ Item 2',
    parent: 'faq-container',
  },

  // 10. FINAL FOOTER CTA
  'final-cta-section': {
    type: { resolvedName: 'Container' },
    isCanvas: false,
    props: {
      bgColor: '#052e16',
      paddingTop: 40,
      paddingBottom: 40,
      paddingLeft: 24,
      paddingRight: 24,
    },
    displayName: 'Pied de Page Final',
    parent: 'ROOT',
    nodes: ['final-cta-title', 'final-cta-button'],
  },
  'final-cta-title': {
    type: { resolvedName: 'Text' },
    isCanvas: false,
    props: {
      text: 'Votre Premier Produit Numérique Commence Ici',
      fontSize: 26,
      textAlign: 'center',
      textColor: '#ffffff',
      fontWeight: 'black',
      marginBottom: 16,
    },
    displayName: 'Titre Final CTA',
    parent: 'final-cta-section',
  },
  'final-cta-button': {
    type: { resolvedName: 'Button' },
    isCanvas: false,
    props: {
      text: '👉 Obtenir Mon Accès Immédiat Pour 19€',
      bgColor: '#22c55e',
      textColor: '#022c22',
      fontSize: 16,
      fontWeight: 'black',
      borderRadius: 999,
      paddingY: 16,
      paddingX: 32,
      align: 'center',
      href: '#pricing',
    },
    displayName: 'Bouton Final CTA',
    parent: 'final-cta-section',
  },
};

// GALERIE TOUS LES TEMPLATES DISPONIBLES
export const ALL_TEMPLATES: PageTemplate[] = [
  {
    id: 'green-digital-sales-page',
    name: '🟢 Digital Product Pro (Template Vert Top-Vente)',
    category: 'SALES_PAGE',
    description: 'Design haut de gamme Vert Émeraude sombre spécial produits digitaux, cours, ebooks et formations. Déjà structuré avec 10 sections hautement convertissantes.',
    badge: '★ TOP CONVERSION',
    badgeColor: 'bg-emerald-500 text-white',
    previewBg: 'from-emerald-950 via-green-900 to-slate-950',
    themeColor: '#22c55e',
    contentJson: GREEN_DIGITAL_SALES_PAGE_JSON,
  },
  {
    id: 'minimal-light-sales-page',
    name: '⚪ Minimalist Clean White (Page de Vente Épurée)',
    category: 'SALES_PAGE',
    description: 'Design ultra-épuré fond blanc et accents bleus modernes, idéal pour coachs, consultants et agences.',
    badge: 'ÉPURÉ & MODERNE',
    badgeColor: 'bg-blue-600 text-white',
    previewBg: 'from-slate-100 via-white to-blue-50',
    themeColor: '#00A0FF',
    contentJson: null,
  },
  {
    id: 'dark-high-ticket-sales-page',
    name: '⚫ Dark Obsidian High-Ticket (Page de Vente Luxe)',
    category: 'SALES_PAGE',
    description: 'Design noir obsidian et dorés néons pour les offres premium, accompagnements et programmes high-ticket.',
    badge: 'LUXE & PREMIUM',
    badgeColor: 'bg-amber-500 text-slate-950',
    previewBg: 'from-slate-950 via-slate-900 to-amber-950',
    themeColor: '#f59e0b',
    contentJson: null,
  },
];
