const { PrismaClient } = require('@prisma/client');
const prisma = new PrismaClient();

async function main() {
  console.log('Seeding 30 products (Notion Templates & Excel Dashboards)...');

  let notionCat = await prisma.productCategory.findUnique({ where: { slug: 'notion' } });
  if (!notionCat) {
    notionCat = await prisma.productCategory.create({
      data: {
        name: 'Templates Notion',
        slug: 'notion',
        description: 'Workspaces, CRM et systèmes d organisation complets sous Notion.',
      },
    });
  }

  let excelCat = await prisma.productCategory.findUnique({ where: { slug: 'excel' } });
  if (!excelCat) {
    excelCat = await prisma.productCategory.create({
      data: {
        name: 'Dashboards Excel',
        slug: 'excel',
        description: 'Tableaux de bord Excel & Google Sheets pour le suivi financier et l activité.',
      },
    });
  }

  const productsData = [
    // --- 15 TEMPLATES NOTION ---
    {
      name: 'Notion Freelance OS — Second Cerveau & CRM',
      slug: 'notion-freelance-os',
      categorySlug: 'notion',
      price: 49,
      compareAtPrice: 89,
      downloadsCount: 184,
      isFeatured: true,
      coverImage: 'https://images.unsplash.com/photo-1499750310107-5fef28a66643?auto=format&fit=crop&w=1000&q=80',
      shortDescription: 'Le système tout-en-un ultime pour gérer votre activité de freelance, vos prospects, vos projets et vos factures.',
      longDescription: `<h3>Système complet d organisation pour Solopreneurs & Freelances</h3><p>Transformez votre manière de travailler avec ce template Notion ultra-structuré. Conçu sur la méthode PARA et GTD.</p>`,
    },
    {
      name: 'Notion Creator OS — Content Factory',
      slug: 'notion-creator-os',
      categorySlug: 'notion',
      price: 39,
      compareAtPrice: 69,
      downloadsCount: 142,
      isFeatured: true,
      coverImage: 'https://images.unsplash.com/photo-1618005182384-a83a8bd57fbe?auto=format&fit=crop&w=1000&q=80',
      shortDescription: 'Planifiez, rédigez et réutilisez tout votre contenu sur LinkedIn, Twitter, YouTube et la Newsletter.',
      longDescription: `<h3>La machine à créer du contenu sans jamais tomber en panne d idées</h3><p>Organisez votre calendrier éditorial, stockez vos idées d articles et analysez les performances de vos publications.</p>`,
    },
    {
      name: 'Notion Life Operating System 2026',
      slug: 'notion-life-os-2026',
      categorySlug: 'notion',
      price: 29,
      compareAtPrice: 49,
      downloadsCount: 96,
      isFeatured: false,
      coverImage: 'https://images.unsplash.com/photo-1484480974693-6ca0a78fb36b?auto=format&fit=crop&w=1000&q=80',
      shortDescription: 'Organisez votre vie personnelle et professionnelle : objectifs, habitudes, routines et finances personnelles.',
      longDescription: `<h3>Pilotez vos objectifs de vie en toute simplicité</h3><p>Un tableau de bord épuré pour aligner vos actions quotidiennes avec vos grandes ambitions stratégiques.</p>`,
    },
    {
      name: 'Notion Agency HQ — Gestion d Équipe & Projets',
      slug: 'notion-agency-hq',
      categorySlug: 'notion',
      price: 79,
      compareAtPrice: 129,
      downloadsCount: 68,
      isFeatured: false,
      coverImage: 'https://images.unsplash.com/photo-1522071820081-009f0129c71c?auto=format&fit=crop&w=1000&q=80',
      shortDescription: 'Le hub central pour agences digitales et studios d experts : équipes, sprints, livrables et wikis.',
      longDescription: `<h3>Le système d exploitation complet pour les petites agences</h3><p>Centralisez toutes les informations de votre agence au même endroit pour collaborer sans friction avec vos équipes.</p>`,
    },
    {
      name: 'Notion Brain — Second Cerveau PARA Method',
      slug: 'notion-brain-para',
      categorySlug: 'notion',
      price: 24,
      compareAtPrice: 39,
      downloadsCount: 112,
      isFeatured: false,
      coverImage: 'https://images.unsplash.com/photo-1456513080510-7bf3a84b82f8?auto=format&fit=crop&w=1000&q=80',
      shortDescription: 'Capturez, organisez et retrouvez n importe quelle note, idée ou ressource grâce à la méthode PARA.',
      longDescription: `<h3>Ne perdez plus jamais une seule idée importante</h3><p>Organisez vos notes selon la méthode éprouvée PARA (Projects, Areas, Resources, Archives) de Tiago Forte.</p>`,
    },
    {
      name: 'Notion Client Portal Pro',
      slug: 'notion-client-portal-pro',
      categorySlug: 'notion',
      price: 34,
      compareAtPrice: 59,
      downloadsCount: 75,
      isFeatured: false,
      coverImage: 'https://images.unsplash.com/photo-1551836022-d5d88e9218df?auto=format&fit=crop&w=1000&q=80',
      shortDescription: 'Impressionnez vos clients avec un portail collaboratif professionnel et personnalisable.',
      longDescription: `<h3>Une expérience client premium dès le premier jour</h3><p>Offrez à vos clients un espace élégant où ils retrouvent le contrat, les livrables, l avancement et les validations.</p>`,
    },
    {
      name: 'Notion Sales & CRM Hub',
      slug: 'notion-sales-crm-hub',
      categorySlug: 'notion',
      price: 29,
      compareAtPrice: 49,
      downloadsCount: 91,
      isFeatured: false,
      coverImage: 'https://images.unsplash.com/photo-1460925895917-afdab827c52f?auto=format&fit=crop&w=1000&q=80',
      shortDescription: 'Suivez vos leads, vos opportunités commerciales et vos relances sans rater un seul contrat.',
      longDescription: `<h3>Le CRM idéal pour les freelances et consultants indépendants</h3><p>Visualisez l état de votre pipe commercial, l historique des échanges et prévoyez vos revenus futurs.</p>`,
    },
    {
      name: 'Notion OKR & Goals Tracker',
      slug: 'notion-okr-goals-tracker',
      categorySlug: 'notion',
      price: 19,
      compareAtPrice: 35,
      downloadsCount: 54,
      isFeatured: false,
      coverImage: 'https://images.unsplash.com/photo-1507679799987-c73779587ccf?auto=format&fit=crop&w=1000&q=80',
      shortDescription: 'Fixez vos objectifs annuels et suivez vos résultats clés (OKRs) trimestre par trimestre.',
      longDescription: `<h3>Transformez vos grandes idées en résultats mesurables</h3><p>Déclinez vos grands objectifs stratégiques en Key Results hebdomadaires.</p>`,
    },
    {
      name: 'Notion Finance & Expense Tracker',
      slug: 'notion-finance-expense-tracker',
      categorySlug: 'notion',
      price: 25,
      compareAtPrice: 45,
      downloadsCount: 88,
      isFeatured: false,
      coverImage: 'https://images.unsplash.com/photo-1554224155-8d04cb21cd6c?auto=format&fit=crop&w=1000&q=80',
      shortDescription: 'Gardez un œil précis sur vos recettes, vos dépenses professionnelles et votre trésorerie.',
      longDescription: `<h3>Le contrôle total de vos finances sur Notion</h3><p>Suivez vos flux de trésorerie, vos abonnements récurrents et générez vos rapports financiers mensuels.</p>`,
    },
    {
      name: 'Notion Product Launch OS',
      slug: 'notion-product-launch-os',
      categorySlug: 'notion',
      price: 45,
      compareAtPrice: 79,
      downloadsCount: 63,
      isFeatured: false,
      coverImage: 'https://images.unsplash.com/photo-1531403009284-440f080d1e12?auto=format&fit=crop&w=1000&q=80',
      shortDescription: 'Planifiez le lancement de vos produits digitaux de la pré-chauffe à la clôture des ventes.',
      longDescription: `<h3>Le rétroplanning ultime pour réussir votre lancement de produit</h3><p>Feuille de route jour par jour, emails de lancement, scripts de vente et partenaires d affiliation.</p>`,
    },
    {
      name: 'Notion Ebook & Course Writing Studio',
      slug: 'notion-ebook-writing-studio',
      categorySlug: 'notion',
      price: 27,
      compareAtPrice: 49,
      downloadsCount: 41,
      isFeatured: false,
      coverImage: 'https://images.unsplash.com/photo-1455390582262-044cdead277a?auto=format&fit=crop&w=1000&q=80',
      shortDescription: 'Rédigez, structurez et éditez vos livres numériques et modules de formation.',
      longDescription: `<h3>Passez de l idée de formation au livre prêt à publier</h3><p>Plan de chapitres, compteur de mots, fiches de révision et ressources bibliographiques.</p>`,
    },
    {
      name: 'Notion Habit & Fitness Tracker',
      slug: 'notion-habit-fitness-tracker',
      categorySlug: 'notion',
      price: 15,
      compareAtPrice: 29,
      downloadsCount: 104,
      isFeatured: false,
      coverImage: 'https://images.unsplash.com/photo-1517838277536-f5f99be501cd?auto=format&fit=crop&w=1000&q=80',
      shortDescription: 'Suivez vos entraînements sportifs, votre nutrition et vos habitudes de bien-être.',
      longDescription: `<h3>Maintenez une discipline de fer au quotidien</h3><p>Programmes de sport, carnet d entraînement et suivi de vos métriques physiques.</p>`,
    },
    {
      name: 'Notion Student & University Hub',
      slug: 'notion-student-university-hub',
      categorySlug: 'notion',
      price: 19,
      compareAtPrice: 35,
      downloadsCount: 135,
      isFeatured: false,
      coverImage: 'https://images.unsplash.com/photo-1434030216411-0b793f4b4173?auto=format&fit=crop&w=1000&q=80',
      shortDescription: 'Organisez vos cours, vos examens, vos devoirs et vos révisions d études supérieures.',
      longDescription: `<h3>Reussissez vos examens avec une organisation irréprochable</h3><p>Emploi du temps interactif, fiches de révision par matière et planning de rendus.</p>`,
    },
    {
      name: 'Notion Event & Webinar Planner',
      slug: 'notion-event-webinar-planner',
      categorySlug: 'notion',
      price: 29,
      compareAtPrice: 49,
      downloadsCount: 38,
      isFeatured: false,
      coverImage: 'https://images.unsplash.com/photo-1511578314322-379afb476865?auto=format&fit=crop&w=1000&q=80',
      shortDescription: 'Organisez vos événements virtuels, ateliers en ligne et webinaires de A à Z.',
      longDescription: `<h3>Déroulé d événement et gestion des intervenants</h3><p>Checklist technique, inscription des participants, scripts de présentation et suivi des inscriptions.</p>`,
    },
    {
      name: 'Notion Job Search & Career Hub',
      slug: 'notion-job-search-hub',
      categorySlug: 'notion',
      price: 19,
      compareAtPrice: 29,
      downloadsCount: 62,
      isFeatured: false,
      coverImage: 'https://images.unsplash.com/photo-1586281380349-632531db7ed4?auto=format&fit=crop&w=1000&q=80',
      shortDescription: 'Suivez vos candidatures, préparez vos entretiens et stockez vos versions de CV.',
      longDescription: `<h3>Décrochez la mission ou le job de vos rêves</h3><p>Tableau de suivi des entreprises cibles, relances réseau et fiches de préparation d entretiens.</p>`,
    },

    // --- 15 DASHBOARDS EXCEL ---
    {
      name: 'Excel Dashboard Trésorerie & Suivi Financier Pro',
      slug: 'excel-dashboard-tresorerie-pro',
      categorySlug: 'excel',
      price: 39,
      compareAtPrice: 69,
      downloadsCount: 245,
      isFeatured: true,
      coverImage: 'https://images.unsplash.com/photo-1551836022-d5d88e9218df?auto=format&fit=crop&w=1000&q=80',
      shortDescription: 'Le tableau de bord financier complet sur Excel pour suivre vos encaissés, décaissés et prévisions.',
      longDescription: `<h3>Pilotez votre trésorerie avec des graphiques dynamiques automatiques</h3><p>Modèle automatisé sous Excel / Google Sheets avec indicateurs clés de solde bancaire et calcul de TVA.</p>`,
    },
    {
      name: 'Excel Dashboard Facturation & Relance Client',
      slug: 'excel-dashboard-facturation-relance',
      categorySlug: 'excel',
      price: 29,
      compareAtPrice: 49,
      downloadsCount: 168,
      isFeatured: true,
      coverImage: 'https://images.unsplash.com/photo-1450133064473-71024230f91b?auto=format&fit=crop&w=1000&q=80',
      shortDescription: 'Générez des factures professionnelles et suivez les impayés et retard de paiement.',
      longDescription: `<h3>Éliminez les retards de paiement et contrôlez vos entrées d argent</h3><p>Modèle automatique avec calcul des jours de retard et bilan d encaissé.</p>`,
    },
    {
      name: 'Excel Dashboard TJM & Rentabilité Projets',
      slug: 'excel-dashboard-tjm-rentabilite',
      categorySlug: 'excel',
      price: 35,
      compareAtPrice: 59,
      downloadsCount: 128,
      isFeatured: false,
      coverImage: 'https://images.unsplash.com/photo-1543269865-cbf427effbad?auto=format&fit=crop&w=1000&q=80',
      shortDescription: 'Calculez votre Taux Journalier Moyen (TJM) idéal et mesurez la rentabilité de chaque contrat.',
      longDescription: `<h3>Fixez vos tarifs sans deviner et maximisez votre marge</h3><p>Prenez en compte vos jours ouvrés réels, vos charges fixes et vos vacances.</p>`,
    },
    {
      name: 'Excel Tableau de Bord Ventes E-commerce & Stripe',
      slug: 'excel-dashboard-ventes-ecommerce',
      categorySlug: 'excel',
      price: 49,
      compareAtPrice: 89,
      downloadsCount: 94,
      isFeatured: false,
      coverImage: 'https://images.unsplash.com/photo-1556742049-0a67daf40954?auto=format&fit=crop&w=1000&q=80',
      shortDescription: 'Importez vos données de vente Stripe / Shopify pour analyser vos marges et votre panier moyen.',
      longDescription: `<h3>Analyse approfondie de la performance de vos produits</h3><p>Visualisez votre chiffre d affaires par produit et par canal d acquisition.</p>`,
    },
    {
      name: 'Excel Business Plan & Prévisionnel 3 Ans',
      slug: 'excel-business-plan-previsionnel',
      categorySlug: 'excel',
      price: 59,
      compareAtPrice: 99,
      downloadsCount: 156,
      isFeatured: false,
      coverImage: 'https://images.unsplash.com/photo-1460925895917-afdab827c52f?auto=format&fit=crop&w=1000&q=80',
      shortDescription: 'Le modèle financier indispensable pour banques, investisseurs et création d entreprise.',
      longDescription: `<h3>Présentez un dossier financier irréprochable et convaincant</h3><p>Compte de résultat prévisionnel, plan de financement et tableau de trésorerie.</p>`,
    },
    {
      name: 'Excel Management de Projet & Gantt Automatique',
      slug: 'excel-gantt-project-management',
      categorySlug: 'excel',
      price: 27,
      compareAtPrice: 45,
      downloadsCount: 115,
      isFeatured: false,
      coverImage: 'https://images.unsplash.com/photo-1507679799987-c73779587ccf?auto=format&fit=crop&w=1000&q=80',
      shortDescription: 'Planning Gantt interactif avec mise en forme conditionnelle et suivi de progression.',
      longDescription: `<h3>Pilotez les jalons de vos projets avec simplicité</h3><p>Diagramme de Gantt avec mise à jour automatique des dates et dépendances.</p>`,
    },
    {
      name: 'Excel Suivi d Investissements & Portefeuille Bourse/Crypto',
      slug: 'excel-investissements-portefeuille',
      categorySlug: 'excel',
      price: 34,
      compareAtPrice: 59,
      downloadsCount: 82,
      isFeatured: false,
      coverImage: 'https://images.unsplash.com/photo-1611974789855-9c2a0a7236a3?auto=format&fit=crop&w=1000&q=80',
      shortDescription: 'Calculez la plus-value globale de vos placements financiers, ETF et cryptomonnaies.',
      longDescription: `<h3>Centralisez l ensemble de vos actifs financiers</h3><p>Calcul automatique des plus-values latentes et réalisées.</p>`,
    },
    {
      name: 'Excel Suivi de Stock & Inventaire Magasin',
      slug: 'excel-suivi-stock-inventaire',
      categorySlug: 'excel',
      price: 29,
      compareAtPrice: 49,
      downloadsCount: 67,
      isFeatured: false,
      coverImage: 'https://images.unsplash.com/photo-1586528116311-ad8dd3c8310d?auto=format&fit=crop&w=1000&q=80',
      shortDescription: 'Alerte automatique de réapprovisionnement, entrées/sorties de marchandise et valeur de stock.',
      longDescription: `<h3>Ne tombez plus jamais en rupture de stock</h3><p>Alerte de niveau de stock minimum et suivi des fournisseurs.</p>`,
    },
    {
      name: 'Excel Budget Personnel & Règle 50/30/20',
      slug: 'excel-budget-personnel-50-30-20',
      categorySlug: 'excel',
      price: 19,
      compareAtPrice: 35,
      downloadsCount: 210,
      isFeatured: false,
      coverImage: 'https://images.unsplash.com/photo-1579621970563-ebec7560ff3e?auto=format&fit=crop&w=1000&q=80',
      shortDescription: 'Reprenez le contrôle de vos finances personnelles avec la règle budgétaire 50/30/20.',
      longDescription: `<h3>Économisez plus chaque mois sans vous priver</h3><p>Ventilation automatique entre besoins essentiels, envies et épargne.</p>`,
    },
    {
      name: 'Excel Calculateur Devis & Marges Commerciales',
      slug: 'excel-calculateur-devis-marges',
      categorySlug: 'excel',
      price: 24,
      compareAtPrice: 39,
      downloadsCount: 78,
      isFeatured: false,
      coverImage: 'https://images.unsplash.com/photo-1554224154-26032ffc0d07?auto=format&fit=crop&w=1000&q=80',
      shortDescription: 'Chiffrez vos prestations et vos produits en incluant vos sous-traitants et votre marge cible.',
      longDescription: `<h3>Proposez des devis rentables à coup sûr</h3><p>Calculateur de coût de revient et marge brute automatique.</p>`,
    },
    {
      name: 'Excel Suivi Kilométrique & Frais de Déplacement',
      slug: 'excel-suivi-kilometrique-frais',
      categorySlug: 'excel',
      price: 15,
      compareAtPrice: 25,
      downloadsCount: 142,
      isFeatured: false,
      coverImage: 'https://images.unsplash.com/photo-1449965408869-eaa3f722e40d?auto=format&fit=crop&w=1000&q=80',
      shortDescription: 'Calculez automatiquement vos indemnités kilométriques selon le barème officiel de l État.',
      longDescription: `<h3>Optimisez vos déductions fiscales lors de votre déclaration</h3><p>Barème de l Administration fiscale mis à jour et historique des trajets.</p>`,
    },
    {
      name: 'Excel Dashboard KPIs Marketing & ROI Publicitaire',
      slug: 'excel-dashboard-kpis-marketing',
      categorySlug: 'excel',
      price: 39,
      compareAtPrice: 69,
      downloadsCount: 59,
      isFeatured: false,
      coverImage: 'https://images.unsplash.com/photo-1460925895917-afdab827c52f?auto=format&fit=crop&w=1000&q=80',
      shortDescription: 'Mesurez le retour sur investissement (ROAS & CAC) de vos campagnes Meta Ads & Google Ads.',
      longDescription: `<h3>Pilotez vos budgets publicitaires comme un professionnel</h3><p>Calcul automatique du coût d acquisition client (CAC) et taux de conversion.</p>`,
    },
    {
      name: 'Excel Tableau de Bord Horaires & Heures Supplémentaires',
      slug: 'excel-dashboard-heures-supplementaires',
      categorySlug: 'excel',
      price: 22,
      compareAtPrice: 39,
      downloadsCount: 93,
      isFeatured: false,
      coverImage: 'https://images.unsplash.com/photo-1508962914676-134849a727f0?auto=format&fit=crop&w=1000&q=80',
      shortDescription: 'Suivez le temps de travail hebdomadaire et le cumul des heures sup pour vos salariés.',
      longDescription: `<h3>Simplifiez la préparation des fiches de paie</h3><p>Calcul des majorations de nuit et de week-end, cumul RTT et absences.</p>`,
    },
    {
      name: 'Excel Dashboard Immobilier & Rendement Locatif',
      slug: 'excel-dashboard-immobilier-rendement',
      categorySlug: 'excel',
      price: 45,
      compareAtPrice: 79,
      downloadsCount: 119,
      isFeatured: false,
      coverImage: 'https://images.unsplash.com/photo-1560518883-ce09059eeffa?auto=format&fit=crop&w=1000&q=80',
      shortDescription: 'Analyse de rentabilité brute/nette d un investissement locatif, cash-flow et fiscalité LMNP.',
      longDescription: `<h3>Simulez vos investissements immobiliers avant d acheter</h3><p>Calcul du cash-flow net d impôt et amortissement LMNP.</p>`,
    },
    {
      name: 'Excel Suivi d Abonnements & Charges Récurrentes',
      slug: 'excel-suivi-abonnements-charges',
      categorySlug: 'excel',
      price: 15,
      compareAtPrice: 25,
      downloadsCount: 86,
      isFeatured: false,
      coverImage: 'https://images.unsplash.com/photo-1563986768609-322da13575f3?auto=format&fit=crop&w=1000&q=80',
      shortDescription: 'Détectez les abonnements inutiles et réduisez vos charges fixes mensuelles.',
      longDescription: `<h3>Traquez les dépenses passives de votre entreprise</h3><p>Calendrier des préélèvements et coût annuel lissé.</p>`,
    },
  ];

  for (const item of productsData) {
    const category = item.categorySlug === 'notion' ? notionCat : excelCat;

    await prisma.product.upsert({
      where: { slug: item.slug },
      update: {
        name: item.name,
        price: item.price,
        compareAtPrice: item.compareAtPrice,
        shortDescription: item.shortDescription,
        longDescription: item.longDescription,
        coverImage: item.coverImage,
        isFreeResource: false,
        downloadsCount: item.downloadsCount,
        isFeatured: item.isFeatured,
        status: 'PUBLISHED',
        productCategoryId: category.id,
      },
      create: {
        name: item.name,
        slug: item.slug,
        price: item.price,
        compareAtPrice: item.compareAtPrice,
        shortDescription: item.shortDescription,
        longDescription: item.longDescription,
        coverImage: item.coverImage,
        isFreeResource: false,
        downloadsCount: item.downloadsCount,
        isFeatured: item.isFeatured,
        status: 'PUBLISHED',
        productCategoryId: category.id,
      },
    });
  }

  console.log('Successfully seeded 30 products into database!');
}

main()
  .catch((e) => {
    console.error(e);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });
